Add TC meta-runners + documentations
octopusden/octopus-base pull request #3
Opened 2023-01-18 14:23 UTC by ozonophore

2023-01-18 14:25 UTC, octopusden approved these changes

2023-01-18 15:37 UTC, pgorbachev requested changes

2023-01-18 16:46 UTC, ozonophore commented on teamcity.meta-runners/CalculateBuildVersion.xml
> +<meta-runner name="CalculateBuildVersion">
Fixed

2023-01-18 16:47 UTC, ozonophore commented on teamcity.meta-runners/README.md
> +- [Calculate the build version](CalculateBuildVersion.xml) - parse a input variable VERSION_TAG with a special format (v{versionMajor}.{versionMinor}.{versionPatch}.{buildCounter}) and increment the
Fixed

2023-01-19 10:15 UTC, pgorbachev submitted a review, later dismissed

2023-01-19 11:15 UTC, pgorbachev requested changes

2023-01-19 11:44 UTC, pgorbachev commented on teamcity.meta-runners/README.md
> +### 1. Compile && UT
Add "Specify RELENG_SKIP=true at project level"

2023-01-19 12:16 UTC, pgorbachev commented
Specify also required changes for API Gateway (new identifier for keycloack client)

2023-01-19 18:03 UTC, ozonophore commented on teamcity.meta-runners/README.md
> +## Pipeline for Employee-service
fixed

2023-01-19 18:11 UTC, pgorbachev commented on teamcity.meta-runners/README.md
> +Add the new keys to ***'f1-config-server / f1-api-gateway-cloud-qa / f1-api-gateway-cloud-qa / spring.security.oauth2.client.registration.keycloak.client-secret'*** and ***'f1-config-server / f1-api-
F1 здесь лишнее

2023-01-20 09:18 UTC, pgorbachev approved these changes

2023-01-20 09:27 UTC, merged